### ISSUE TITLE
Conflict with react-bootstrap

### ISSUE THREAD

**Issue by gusdaud-zz** [jamhall/react-dropdown-menu#1]
Hi, this component uses `dropdown-menu` as its classname which conflicts with React Bootstrap library (https://react-bootstrap.github.io/) as it uses the same name.

My suggestion is to replace with `rdropdown-menu` which I tested and will work fine.

Thanks for the great work.

**Comment by gusdaud-zz** [comment]
Hey, I did some improvements and published them to another repo. Here are the changes:
https://github.com/gusdaud/rdropdown/compare/improvements?expand=1
- _fix_ Fix in package.json to support `npm start` in windows
- _fix_ Inclusion of Promise polyfill in package.json devDependencies for examples to work in Internet Explorer;
- _fix_ Changed css class from `dropdown-menu` to `rdropdown-menu` to prevent a conflict with React-bootstrap class;
- _improved_ Now component renders directly in document body to prevent it being overlapped by other components at the same level as its parent.

Feel free to merge if you find them helpful.

**Comment by jamhall** [comment]
Hello! Great changes!
- fix Fix in package.json to support npm start in windows

Thank you
- fix Changed css class from dropdown-menu to rdropdown-menu to prevent a conflict with React-bootstrap class;

Damn, I should have realised this. Oops. Thanks!
- improved Now component renders directly in document body to prevent it being overlapped by other components at the same level as its parent.

Awesome!

I have merged your changes into the master branch.
