### ISSUE TITLE
onSearch return promise

### ISSUE THREAD

**Issue by gusdaud-zz** [jamhall/react-dropdown-menu#2]
I think it would be great if `onSearch` property could also return a promise. 
So application may load search data from an external service.

I've implemented this in my fork:
https://github.com/gusdaud/rdropdown/compare/improvements...search-with-promise?expand=1

Feel free to merge it if you like.

**Comment by jamhall** [comment]
Hello,

I like the idea of the onSearch property also returning a promise. I have merged your search-with-promise branch into my master branch.

Tomorrow, I will add a prop to allow the search timeout to be configurable.

Thank you again for your changes. They are much appreciated.

**Comment by jamhall** [comment]
Hello @gusdaud  - [v1.1.0](https://github.com/jamhall/rdropdown/releases/tag/v1.1.0) has been published with your changes. Thanks.

**Comment by gusdaud-zz** [comment]
All right @jamhall. Thank you too so much for the excellent work. see ya
